version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Check formula style
          command: |
            # From: https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/master/.github/PULL_REQUEST_TEMPLATE.md
            brew audit --online --strict ./wrangler-cli.rb
            brew style ./wrangler-cli.rb
      - run:
          name: Install and test stable
          command: |
            # From: https://docs.brew.sh/Formula-Cookbook
            brew install --verbose ./wrangler-cli.rb
            brew test ./wrangler-cli.rb
      - run:
          name: Install and test devel
          command: |
            # Uninstall stable
            brew uninstall wrangler-cli
            # Install and test the development version
            brew install --verbose --devel ./wrangler-cli.rb
            brew test --devel ./wrangler-cli.rb
