name: CI
on: [push]
jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew audit --online --strict ./wrangler-cli.rb
  style:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew style ./wrangler-cli.rb
  test-stable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew install --verbose ./wrangler-cli.rb
      - run: brew test ./wrangler-cli.rb
  test-head:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew install --verbose --head ./wrangler-cli.rb
      - run: brew test --head ./wrangler-cli.rb
