name: CI
on: [push]
checkout: &checkout
  uses: actions/checkout@v1
macos: &macos
  runs-on: macos-latest
jobs:
  audit:
    <<: *macos
    steps:
      - *checkout
      - name: Audit formula
        run: brew audit --online --strict ./wrangler-cli.rb
  style:
    <<: *macos
    steps:
      - *checkout
      - name: Check formula style
        run: brew style ./wrangler-cli.rb
  test-stable:
    <<: *macos
    steps:
      - *checkout
      - name: Install
        run: brew install --verbose ./wrangler-cli.rb
      - name: Test
        run: brew test ./wrangler-cli.rb
  test-devel:
    <<: *macos
    steps:
      - *checkout
      - name: Install
        run: brew install --verbose --devel ./wrangler-cli.rb
      - name: Test
        run: brew test --devel ./wrangler-cli.rb
# audit and style are adapted from the AdoptOpenJDK formula.
# test-* comes from the Formula Cookbook.
