name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit formula
        run: brew audit --online --strict ./wrangler-cli.rb
      - name: Check formula style
        run: brew style ./wrangler-cli.rb
      - name: "[stable] Install"
        run: brew install --verbose ./wrangler-cli.rb
      - name: "[stable] Test"
        run: brew test ./wrangler-cli.rb
      - name: "[stable] Uninstall"
        run: brew uninstall wrangler-cli
      - name: "[devel] Install"
        run: brew install --verbose --devel ./wrangler-cli.rb
      - name: "[devel] Test"
        run: brew test --devel ./wrangler-cli.rb
