name: CI
on: [push]
jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit formula
        run: brew audit --online --strict ./wrangler-cli.rb
  style:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check formula style
        run: brew style ./wrangler-cli.rb
  test-stable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: "[stable] Install"
        run: brew install --verbose ./wrangler-cli.rb
      - name: "[stable] Test"
        run: brew test ./wrangler-cli.rb
  test-devel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: "[devel] Install"
        run: brew install --verbose --devel ./wrangler-cli.rb
      - name: "[devel] Test"
        run: brew test --devel ./wrangler-cli.rb
# audit and style are adapted from the AdoptOpenJDK formula.
# test-* comes from the Formula Cookbook.
